// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdfdxyolmlkveckeqcdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZmR4eW9sbWxrdmVja2VxY2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTcxNDIsImV4cCI6MjA2OTQ5MzE0Mn0.eQ4kPpfadbfCPB6sScJLsN6nFZJ5wlPdLU1_WJWeAQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});